### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by anatox** [Cobraeti/docker-pyload#1]
Service doesn't start with no error at any configuration. It seems some files are missing.

**Comment by Cobraeti** [comment]
Hi @anatox ,
I can't test right now, but your change seems good as it reminds me some steps from the time I first released this image, so thank you for correcting my mistake ;)
I just accepted your pull request, so the build might end up in a few minutes.  
Sorry for not maintaining correctly this container recently, as I was a little short in time to stay long enougth on this subject ^^
As soon as I have some time to spend on it, I will reconfigure the versionning on Dockerhub, so older working images could be used if the latest has not built correctly...
