### ISSUE TITLE
ERROR	pycurl error 1: Protocol ttps not supported or disabled in libcurl

### ISSUE THREAD

**Issue by maschhoff** [Cobraeti/docker-pyload#5]
Trying to download from https I get:

ERROR	pycurl error 1: Protocol ttps not supported or disabled in libcurl

**Comment by Cobraeti** [comment]
Hello @maschhoff, haven't you missed the "h" of "https" in your URL ?
If not, I would suggest you to post on [the official pyload's repo](https://github.com/pyload/pyload) pointed in the README.md.
Mine is just here to provide a Docker container of this soft that conforms as most as I could to what [LinuxServer.io](https://github.com/linuxserver) made for other softs like Deluge, MariaDb and many more.
If this needs a fix on pyload source, don't hesitate to come here when they fixes it, so I will launch a new build of this container :wink:

**Comment by Cobraeti** [comment]
Closing as this issue has not been updated since my last comment
