### ISSUE TITLE
Push new build to Dockerhub

### ISSUE THREAD

**Issue by ryester19** [Cobraeti/docker-pyload#6]
Hello. Since the last build that was pushed 8 months ago, there has been some significant code changes done to the stable branch such as the addition of a new modern theme and support for manual reCAPTCHA solving.

Can you please post a new build to your Docker Hub page?

**Comment by Cobraeti** [comment]
Build launched for tags 0.4.9_20181231 and latest with the last available commits from pyload/pyload
